module ActiveRecord
  class Base
    # https://github.com/ruby/gem_rbs_collection/blob/34275028974d6352fe7666a6e833def7a6efb4a5/gems/activerecord/6.0/activerecord-generated.rbs#L19701
    # https://github.com/rails/rails/blob/v7.0.4.3/activerecord/lib/active_record/querying.rb#L5-L22
    # https://github.com/rails/rails/blob/v7.0.4.3/activerecord/lib/active_record/relation.rb#L218-L222
    def self.create_or_find_by!: (untyped attributes) { (instance) -> untyped } -> instance
  end

  class Migration
    # https://github.com/rails/rails/blob/v7.0.4.3/activerecord/lib/active_record/migration.rb#L918-L935
    # https://github.com/rails/rails/blob/v7.0.4.3/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L299-L344
    include ConnectionAdapters::SchemaStatements
  end
end
