class Thor
  class Group
  end

  module Actions
    type file_manipulation_config = { verbose: bool, mode: :preserve | untyped }

    # https://github.com/rails/thor/blob/v1.2.1/lib/thor/actions/file_manipulation.rb#L21-L35
    def copy_file: (String source, ?file_manipulation_config config) ?{ (String content) -> String } -> void
                 | (String source, String destination, ?file_manipulation_config config) ?{ (String content) -> String } -> void

    # https://github.com/rails/thor/blob/v1.3.2/lib/thor/actions/file_manipulation.rb#L262-L275
    def gsub_file: (String path, Regexp | String flag, String replacement, ?Hash[Symbol, bool] config) -> void
  end
end
