# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "10:00"
      timezone: Asia/Tokyo
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "10:00"
      timezone: Asia/Tokyo
    groups:
      rails:
        patterns:
          - "action*"
          - "active*"
          - "rails"
          - "railties"
      rspec:
        patterns:
          - "rspec*"
      rubocop:
        patterns:
          - "rubocop*"
    allow:
      - dependency-type: all
    open-pull-requests-limit: 15
