class CheckAll
  TASKNAMES: Array[Symbol]
  LINE: String
  TITLE_TEMPLATE: String

  attr_reader failed_commands: Array[String]

  def self.call: () -> void

  def call: () -> void

  private

  def executor: () -> ^(*String) -> void
  def output_result: () -> void
end
