name: Checks

on:
  push:
    branches:
      - 1-0-stable
  pull_request:

jobs:
  test:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.5"
          - "2.6"
          - "2.7"
        rails-version:
          - "~> 5.1.0"
          - "~> 5.2.0"
          - "~> 6.0.0"
          - "~> 6.1.0"
        addressable-version:
          - "~> 2.4.0"
          - "~> 2.5.0"
          - "~> 2.6.0"
          - "~> 2.7.0"
          - "~> 2.8.0"
    runs-on: ubuntu-latest
    env:
      # Ignore `Gemfile.lock` on CI.
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile.ci

      RAILS_VERSION: ${{ matrix.rails-version }}
      ADDRESSABLE_VERSION: ${{ matrix.addressable-version }}
    name: >-
      Test --
      Ruby ${{ matrix.ruby-version }} &&
      Rails ${{ matrix.rails-version }} &&
      Addressable ${{ matrix.addressable-version }}
    steps:
      - uses: actions/checkout@v4

      # https://github.com/ruby/setup-ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Setup database
        run: bin/rails db:migrate RAILS_ENV=test
        timeout-minutes: 5

      - name: RSpec
        run: bundle exec rake spec
        timeout-minutes: 5

  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      # Ignore `Gemfile.lock` on CI.
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile.ci

      RAILS_VERSION: "~> 5.2.0"
      ADDRESSABLE_VERSION: "~> 2.8.0"
    name: Lint
    steps:
      - uses: actions/checkout@v4

      # https://github.com/ruby/setup-ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true

      - name: RuboCop
        run: bundle exec rake rubocop
        timeout-minutes: 5

  documentation-check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      # Ignore `Gemfile.lock` on CI.
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile.ci

      RAILS_VERSION: "~> 5.2.0"
      ADDRESSABLE_VERSION: "~> 2.8.0"
    name: Documentation syntax check
    steps:
      - uses: actions/checkout@v4

      # https://github.com/ruby/setup-ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true

      - name: Check YARD docs
        run: bundle exec rake yard:check
        timeout-minutes: 5
