name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rspec:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "3.1"
          - "ruby"
        rails-version:
          - ""
        addressable-version:
          - "~> 2.4.0"
          - "~> 2.5.0"
          - "~> 2.6.0"
          - "~> 2.7.0"
          - ""
    runs-on: ubuntu-latest
    env:
      # Ignore `Gemfile.lock` on CI.
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile.ci

      RAILS_VERSION: ${{ matrix.rails-version }}
      ADDRESSABLE_VERSION: ${{ matrix.addressable-version }}
    steps:
      - uses: actions/checkout@v3

      # https://github.com/ruby/setup-ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: RSpec
        run: bundle exec rake spec
        timeout-minutes: 5

  rubocop:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://github.com/ruby/setup-ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - name: RuboCop
        run: bundle exec rake rubocop
        timeout-minutes: 5

  steep:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://github.com/ruby/setup-ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - name: Run typecheck
        run: |
          bundle exec rake steep:prepare
          bundle exec rake steep:check
        timeout-minutes: 5

  yard-check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://github.com/ruby/setup-ruby
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - name: Check YARD docs
        run: bundle exec rake yard:check
        timeout-minutes: 5
